export const REDUCE_NPC_HEALTH = 'REDUCE_NPC_HEALTH';
export const SET_NPC_STATE = 'SET_NPC_STATE';
export const SET_JAB_LEFT_STATE = 'SET_JAB_LEFT_STATE';
export const SET_CROSS_LEFT_STATE = 'SET_CROSS_LEFT_STATE';

export const SET_PATTERN_ONE_SAGA_STATE = 'SET_PATTERN_ONE_SAGA_STATE';

export const SET_SAGA = 'SET_SAGA';
export const SET_SAGA_STATE = 'SET_SAGA_STATE';



